services:
  postgres:
    image: postgres:latest
    container_name: my_db_cp
    env_file:
      - env.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: my_redis
    env_file:
      - env.env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "redis_password"]
    restart: always

volumes:
  postgres_data:
  redis_data:
