
services:
  postgres:
    image: postgres:latest
    container_name: my_db_cp
    env_file:
      - env.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
